### ISSUE TITLE
works in browser?

### ISSUE THREAD

**Issue by abhijithvijayan** [futoin/util-js-hkdf#2]
Any chance this package works in browser?

I want to use HMAC-based Extract-and-Expand Key Derivation Function (HKDF) within a browser. If it doesn't work on browser, could you point me to a package for browser?

**Comment by andvgal** [comment]
@abhijithvijayan the fundamental requirement is Node.js-like API for `crypto` dependency. 

You can use `webpack` to provide an implementation of that. For example, it can substitute with [`node-libs-browser`](https://github.com/webpack/node-libs-browser) which uses `crypto-browserify` in turn. Both deprecated though.

You can also, override resolution to own implementation using e.g. `crypto-js`. You feel some other option is necessary, please suggest one.

**Comment by abhijithvijayan** [comment]
@andvgal I want to use this in a react-native project, since it uses webpack, it might work right!
Instead of using the deprecated, Can the `crypto-js` provide the HKDF like you were saying?

All I need is to combine a 16byte salt and email address to generate a 32byte salt using hkdf.

**Comment by andvgal** [comment]
I'll look into this a bit later today. I see some API abstraction is necessary with default implementations both for Node.js and for modern browser.

**Comment by abhijithvijayan** [comment]
@andvgal Thanks.

I actually got an output. I am not sure if this was the expected as intended.

![Screenshot from 2019-06-20 19-43-09](https://user-images.githubusercontent.com/34790378/59856071-cbca0200-9393-11e9-89bc-52c60cd5e7e5.png)

**Comment by andvgal** [comment]
@abhijithvijayan after a closer look, another problem is use of Node-specific `Buffer`.

Basically, it means that whole functionality needs to be rewritten for browser-specific case using native JS Arrays and passing HMAC function as parameter.

Due to the way, how CryptoJS is designed, it's better to ask them to add HKDF support what is really just a few lines of code. I see no reason to modify `futoin-hkdf` at the moment.

Also, I am not sure that your particular case requires HKDF. If it's not a specification requirement then you may use just some good hash function or PBKDF2.

**Comment by andvgal** [comment]
The output is not from the package, BTW.

I am closing the issue for now.

**Comment by panva** [comment]
HKDF is natively supported in browsers through [WebCrypto](https://www.w3.org/TR/WebCryptoAPI/#hkdf)
